### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by averyfreeman** [sherrillmix/glmnetPlotR#1]
Hi

I am not actually reporting a bug w/ your plotting code (which looks quite nice)

I'm actually writing to report that your blog is down, I found it looking for syntax highlighting, you're referenced in this StackExchange post:  https://askubuntu.com/questions/405960/can-cat-show-files-using-code-markup-in-colors

Looks like your entire personal site is having issues - referenced images not loading, etc.

Just thought you might want to know, didn't know else how to get ahold of you other than this.

**Comment by sherrillmix** [comment]
Thanks for the heads up. I recently moved hosting and looks like the tiny VM it's running on isn't quite up to snuff. A restart seems to have fixed things. Thanks again.

**Comment by averyfreeman** [comment]
Hey, no problem, glad it was helpful.  Excited to see the syntax highlighting how-to.  Looks like you really know your stuff!
